apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  # add oss tag for objects running 3rd party software
  - target:
      version: v1
      group: apps
      kind: Deployment
    patch: &oss-patch |-
      - op: add
        path: /metadata/annotations/app.uw.systems~1tags.oss
        value: "true"
  - target:
      version: v1
      group: apps
      kind: StatefulSet
    patch: *oss-patch
