apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml

patches:
  - path: fix-script-cm.yaml

components:
  - ../../components/bitnami-common
  - ../../components/opslevel
