commonAnnotations:
  "app.uw.systems/repos": "https://github.com/utilitywarehouse/shared-kustomize-bases/tree/main/redis"

auth:
  existingSecret: "redis"

# redis replicated instance
architecture: "replication"

metrics:
  enabled: true

  # todo: change resources
  resources:
    requests:
      cpu: "10m"
      memory: "20Mi"
    limits:
      cpu: "100m"
      memory: "100Mi"

sentinel:
  enabled: true
  # original chart disables commands flushdb and flushall.
  # we don't want to do that
  disableCommands: ""

  resources:
    requests:
      cpu: "10m"
      memory: "10Mi"
    limits:
      cpu: "100m"
      memory: "100Mi"

replica:
  # original chart disables commands flushdb and flushall.
  # we don't want to do that
  disableCommands: ""

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
