apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - elasticsearch.yaml

patches:
  # Replace the env variables containing the hostname with namespace
  - path: fix-hosts.yaml
  # remove empty pod annotations, as in Kustomize 5.0.x kustomize generates them as strings with value "null" instead of just null, and they can not be applied.
  # added this issue in kustomize: https://github.com/kubernetes-sigs/kustomize/issues/5171
  - patch: |-
      - op: test
        path: /spec/template/metadata/annotations
        value: null
      - op: remove
        path: /spec/template/metadata/annotations
    target:
      kind: StatefulSet
      name: elasticsearch-master

components:
  - ../../components/bitnami-common
  - ../../components/opslevel

# Patch bitnami repo to bitnamilegacy to continue working after the 28th of
# August 2025
images:
  - name: docker.io/bitnami/kibana
    newName: docker.io/bitnamilegacy/kibana
  - name: docker.io/bitnami/elasticsearch
    newName: docker.io/bitnamilegacy/elasticsearch
  - name: docker.io/bitnami/elasticsearch-exporter
    newName: docker.io/bitnamilegacy/elasticsearch-exporter
