apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - elasticsearch.yaml

patches:
  # Replace the env variables containing the hostname with namespace
  - path: fix-hosts.yaml

components:
  - ../../components/bitnami-common
