#!/bin/bash

set -o errexit -o pipefail -o nounset

mkdir -p ${NS}/${NAME}/upstream


# Fetch from helm repo: https://github.com/bitnami/charts/tree/main/bitnami/redis
helm repo add bitnami https://charts.bitnami.com/bitnami

helm template "${NAME}" bitnami/redis --version "${BITNAMI_REDIS_RELEASE}" \
  --set fullnameOverride="${NAME}" \
  --set nameOverride="${NAME}" \
  --set commonAnnotations."app\.uw\.systems\/description"="${OPSLEVEL_APP_DESCRIPTION}" \
  --set commonAnnotations."app\.uw\.systems\/tier"="${OPSLEVEL_APP_TIER}" \
  --set commonAnnotations."app\.uw\.systems\/repos"="https://github.com/utilitywarehouse/shared-kustomize-bases/tree/main/redis/bitnami" \
  --set auth.existingSecret="${REDIS_SECRET_NAME}" \
  --set master.resources.requests.cpu="${MASTER_CPU_REQUEST}" \
  --set master.resources.limits.cpu="${MASTER_CPU_LIMIT}" \
  --set master.resources.requests.memory="${MASTER_MEMORY_REQUEST}" \
  --set master.resources.limits.memory="${MASTER_MEMORY_LIMIT}" \
  --set replica.resources.requests.cpu="${REPLICA_CPU_REQUEST}" \
  --set replica.resources.limits.cpu="${REPLICA_CPU_LIMIT}" \
  --set replica.resources.requests.memory="${REPLICA_MEMORY_REQUEST}" \
  --set replica.resources.limits.memory="${REPLICA_MEMORY_LIMIT}" \
  --namespace "${NS}"  > "${NS}"/"${NAME}"/upstream/redis.yaml

cp gen-yaml/clean-upstream-kustomize-template.yaml "${NS}"/"${NAME}"/upstream/kustomization.yaml

if [ ! -f "${NS}"/"${NAME}"/kustomization.yaml ]; then
cp gen-yaml/namespace-kustomize-template.yaml "${NS}"/"${NAME}"/kustomization.yaml
fi
