#!/bin/sh

mkdir -p ${NS}/${NAME}/upstream

# Fetch from helm repo: https://github.com/bitnami/charts/tree/main/bitnami/kafka#installing-the-chart
helm repo add bitnami https://charts.bitnami.com/bitnami
helm template ${BITNAMI_REDIS_RELEASE} bitnami/redis --version ${BITNAMI_REDIS_RELEASE} \
--set fullnameOverride=${NAME} \
--set nameOverride=${NAME} \
--namespace ${NS}  > ${NS}/${NAME}/upstream/redis.yaml

cat gen-yaml/clean-upstream-kustomize-template.yaml > ${NS}/${NAME}/upstream/kustomization.yaml

if [ ! -f ${NS}/${NAME}/kustomization.yaml ]; then
cat gen-yaml/namespace-kustomize-template.yaml > ${NS}/${NAME}/kustomization.yaml
fi
