apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- ssh://github.com/utilitywarehouse/shared-kustomize-bases//elasticsearch/manifests?ref=v0.0.0
  - ../manifests
  - ingress.yaml

# OpsLevel annotations
commonAnnotations:
  "app.uw.systems/description": "some es instance"
  "app.uw.systems/tier": "tier_4"

patches:
  # changing the heap size
  - path: env-patch.yaml
  # PVC size
  - target:
      kind: StatefulSet
      name: elasticsearch-master
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 10Gi
  # Resource requests and limits
  - target:
      kind: StatefulSet
      name: elasticsearch-master
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "4Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "8Gi"
