apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      component: redis
    includeSelectors: true
    includeTemplates: true

resources:
  - init-job.yaml
  - statefulset.yaml
  - service.yaml

configMapGenerator:
  - name: redis-env
    envs:
      - config/redis-env
  - name: redis-config
    files:
      - config/redis.conf

secretGenerator:
  - name: redis-password
    envs:
      - secrets/password

images:
  - name: redis
    newTag: 7.2.4