---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /__/metrics
    prometheus.io/port: "8081"
    uw.health.aggregator.port: "8081"
    uw.health.aggregator.enable: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
    - name: metric
      port: 8081
  selector:
    app: redis