apiVersion: batch/v1
kind: Job
metadata:
  # job to be run once to initialise the backup by creating a
  # "Backup Schedule", docs: https://www.cockroachlabs.com/docs/stable/create-schedule-for-backup
  # upon failures of this job (e.g. missing env vars/configuration) you
  # should manually delete it so it can be recreated
  name: cockroach-backup-init
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
        - name: backup-init
          image: cockroachdb
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash" ]
          args: ["-c", "/opt/scripts/wait-for-cluster-to-be-ready.sh && /opt/scripts/backup-bootstrap.sh" ]
          env:
            - name: COCKROACH_HOST
              valueFrom:
                configMapKeyRef:
                  name: cockroach
                  key: cockroach.host
            - name: COCKROACH_PORT
              valueFrom:
                configMapKeyRef:
                  name: cockroach
                  key: cockroach.port
            - name: COCKROACH_CERTS_DIR
              value: "/cockroach-certs/"
            - name: BACKUP_SCHEDULE
              valueFrom:
                configMapKeyRef:
                  name: cockroach.backup.config
                  key: schedule
            - name: BACKUP_DESTINATION_URL
              valueFrom:
                configMapKeyRef:
                  name: cockroach.backup.config
                  key: destination.url
          volumeMounts:
            - name: client-certs
              mountPath: /cockroach-certs
            - name: cockroachdb-scripts
              mountPath: /opt/scripts
              readOnly: true
          resources:
            requests:
              cpu: 0
              memory: 128Mi
            limits:
              cpu: 1
              memory: 512Mi
      restartPolicy: OnFailure
      volumes:
        - name: client-certs
          projected:
            sources:
              - secret:
                  name: cockroachdb.client.root
                  items:
                    - key: ca.crt
                      path: ca.crt
                    - key: tls.crt
                      path: client.root.crt
                    - key: tls.key
                      path: client.root.key
            defaultMode: 256
        - name: cockroachdb-scripts
          configMap:
            name: cockroachdb-scripts
            defaultMode: 0777
