# This manifests return error "unable to parse SM or JSON patch" for kustomize versions lower than v5.2.1, as they don't support multiple patches in one file

# https://www.cockroachlabs.com/docs/stable/authentication#using-cockroach-cert-or-openssl-commands
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  template:
    spec:
      volumes:
        - name: certs
          secret:
            $patch: delete
          projected:
            sources:
              - secret:
                  name: cockroachdb.node
                  items:
                    - key: ca.crt
                      path: ca.crt
                    - key: tls.crt
                      path: node.crt
                    - key: tls.key
                      path: node.key
            defaultMode: 256
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cockroach-init
spec:
  template:
    spec:
      volumes:
        - name: client-certs
          secret:
            $patch: delete
          projected:
            sources:
              - secret:
                  name: cockroachdb.client.root
                  items:
                    - key: ca.crt
                      path: ca.crt
                    - key: tls.crt
                      path: client.root.crt
                    - key: tls.key
                      path: client.root.key
            defaultMode: 256
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroachdb-client
spec:
  template:
    spec:
      volumes:
        - name: client-certs
          secret:
            $patch: delete
          projected:
            sources:
              - secret:
                  name: cockroachdb.client.root
                  items:
                    - key: ca.crt
                      path: ca.crt
                    - key: tls.crt
                      path: client.root.crt
                    - key: tls.key
                      path: client.root.key
            defaultMode: 256
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cockroach-backup-init
spec:
  template:
    spec:
      volumes:
        - name: client-certs
          secret:
            $patch: delete
          projected:
            sources:
              - secret:
                  name: cockroachdb.client.root
                  items:
                    - key: ca.crt
                      path: ca.crt
                    - key: tls.crt
                      path: client.root.crt
                    - key: tls.key
                      path: client.root.key
            defaultMode: 256
