apiVersion: batch/v1
kind: Job
metadata:
  name: cockroach-init
  labels:
    app: cockroachdb
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
        - name: cluster-init
          image: cockroachdb
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: client-certs
              mountPath: /cockroach/cockroach-certs
          env:
            - name: COCKROACH_HOST
              valueFrom:
                configMapKeyRef:
                  name: cockroach
                  key: cockroach.host
          command:
            - "/bin/bash"
            - "-c"
            - "/cockroach/cockroach init --certs-dir=/cockroach/cockroach-certs --port=26357 2>&1 | grep 'initialized'"
          resources:
            requests:
              cpu: 0
              memory: 128Mi
            limits:
              cpu: 1
              memory: 512Mi
      restartPolicy: OnFailure
      volumes:
        - name: client-certs
          projected:
            sources:
              - secret:
                  name: cockroachdb.client.root
                  items:
                    - key: ca.crt
                      path: ca.crt
                    - key: tls.crt
                      path: client.root.crt
                    - key: tls.key
                      path: client.root.key
            defaultMode: 256
