apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- ssh://github.com/utilitywarehouse/shared-kustomize-bases//es-topic-indexer/manifests?ref=v0.0.0
  - ../manifests


# Add prefix to name
namePrefix: sample-event-

# OpsLevel annotations
commonAnnotations:
  "app.uw.systems/description": "Sample events indexer"
  "app.uw.systems/tier": "tier_4"

patches:
  - path: indexer-params.yaml
  - path: kafka-certificate.yaml
