apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: crm-postgres-backup
          containers:
            - name: postgres-backup
              image: eeshugerman/postgres-backup-s3:16
              env:
                - name: S3_BUCKET
                  value: "uw-dev-energy-crm-postgres-backup"
                - name: S3_PREFIX
                  value: "backups"
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: crm-graphql-postgres-secrets
                      key: user
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: crm-graphql-postgres-secrets
                      key: password
                - name: POSTGRES_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: crm-graphql-postgres-secrets
                      key: database
          volumes:
            - name: postgres-backup-pvc
              persistentVolumeClaim:
                claimName: crm-graphql-backup-pvc
