apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namePrefix: crm-graphql
#namespace: "energy-platform"
#commonLabels:
#  app: crm-graphql-postgres
resources:
  - http://github.com/utilitywarehouse/shared-kustomize-bases//postgresql/manifests?ref=marcin-postgres-test
secretGenerator:
  - name: postgresql
    envs:
      - secrets/postgres.properties
    options:
      disableNameSuffixHash: true
patches:
#  - path: backup.yaml
  - path: backup-pvc.yaml
#  - path: postgres.yaml
