apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: dev-enablement
spec:
  volumeClaimTemplates:
    - spec:
        resources:
          requests:
            storage: 70Gi
