apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ssh://github.com/utilitywarehouse/shared-kustomize-bases//redis/manifests/dev-enablement/redis-shared?ref=v0.0.0
  #- ../manifests


# Add prefix to name
namePrefix: service-cache-

# OpsLevel annotations
commonAnnotations:
 "app.uw.systems/description": "cache for some service"
 "app.uw.systems/tier": "tier_4"

patches:
  # replace namespace
  - target:
      kind: .*
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: "some-namespace"
  # Resource requests and limits
  - target:
      kind: StatefulSet
      name: redis-shared-master
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "2Gi"


# Redis password secret
secretGenerator:
  - name: redis
    envs:
      - secrets/redis-secret.yaml
    options:
      disableNameSuffixHash: true
