apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/utilitywarehouse/shared-kustomize-bases//cockroachdb/manifests-cert-manager
  - db-init-manifests/example-database
# sa.yaml and configmap cockroach.backup.config are resources necessary to add the backup.
# If your use case excludes the usage of backups, use patch `disable-backup.yaml`
  - sa.yaml

# OpsLevel annotations
commonAnnotations:
  "app.uw.systems/description": "Cockroachdb instance used to store ..."
  "app.uw.systems/tier": "tier_1"

patches:
  - path: dns-names-patch.yaml
  - path: cockroach.yaml

configMapGenerator:
  - name: cockroach
    envs:
      - config/cockroach
  - name: cockroach.backup.config
    envs:
      - config/backup-config
