apiVersion: batch/v1
kind: Job
metadata:
  name: cockroach-db-init
spec:
  template:
    spec:
      containers:
        - name: db-init
          env:
            - name: DB_NAME
              value: "example_database"
            - name: DB_USER
              value: "example_user"
