apiVersion: batch/v1
kind: Job
metadata:
  name: cockroach-db-init
spec:
  template:
    spec:
      containers:
        - name: db-init
          env:
            # name of the DB that the init will should create
            - name: DB_NAME
              value: "example_database"
            # name of the user that the init job will grant access on the DB to
            - name: DB_USER
              value: "example_user"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cockroach-client
spec:
  commonName: example_user
  secretName: cockroachdb.client.example-user
