apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# similar kustomize file should exist for every database/ user pair

resources:
  - github.com/utilitywarehouse/shared-kustomize-bases//cockroachdb/manifests-cert-manager/db-init?ref=DENA-603

namePrefix: example-database-

patches:
  - path: example-database-init-job.yaml
  - patch: |-
      - op: replace
        path: /spec/commonName
        value: "example_user"
      - op: replace
        path: /spec/secretName
        value: "cockroachdb.client.example-user"
    target:
      kind: Certificate
      name: cockroach-client
      version: v1
