apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# these patches should be repeated for every database/ user pair
patches:
  # This patch creates new db- init job
  - patch: |-
      - op: replace
        path: /metadata/name
        value: example-database-cockroachdb-init
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: "example_database"
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: "example_user"
    target:
      kind: Job
      name: cockroach-init
      version: v1
  # This patch creates new client cert (to be mounted within client)
  - patch: |-
      - op: replace
        path: /metadata/name
        value: cockroachdb-example-user 
      - op: replace
        path: /spec/commonName
        value: "example_user"
      - op: replace
        path: /spec/secretName
        value: "cockroachdb.client.example-user"
    target:
      kind: Certificate
      name: cockroach-userName
      version: v1
